services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Code mount
      - sqlite_data:/app/data  # Database mount directory
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DATABASE_URL=sqlite:///./data/shortener.db  # Set database URL
      - SHORT_URL_LENGTH=6  # Set short URL length
    networks:
      - shortener-network
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - shortener-network
    command: npm run dev -- --host

networks:
  shortener-network:
    driver: bridge

volumes:
  sqlite_data:
    driver: local
